[package]
name = "race-results"
version = "0.1.0"
edition = "2021"

[lib]
name = "race_results"

[dependencies]
anyinput = "0.1.6"
include-flate = "0.2.0"

[dev-dependencies]
itertools = "0.10.5"
regex = "1.8.4"

[profile.release]
debug = false
opt-level = "z"
lto = true
codegen-units = 1
