[package]
name = "web1"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
# cmk are features still needed?
race-results = { path = "../..", features = [
    "alloc",
], default-features = false }
